### ISSUE TITLE
running the testsuite

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/v8-native-prototype#110]
Is there are recommend way to run the wasm test suite on the v8? It doesn't seem to have the test semantics implemented. Also sidenote: Is it appropriate for me to file bugs and questions here (now that development is in the v8 repo)?

**Comment by titzer** [comment]
sexpr-wasm-prototype has scripts to run the tests against V8.

This repo is pretty much dead, so feel free to file V8 bugs or just send mail if something isn't working.
