### ISSUE TITLE
Understanding the wasm prototype

### ISSUE THREAD

**Issue by bobvanluijt** [WebAssembly/v8-native-prototype#111]
In Chrome, the Wasm prototype has four functions:
1) `instantiateModule`
2) `instantiateModuleFromAsm`
3) `verifyFunction`
4) `verifyModule`

Where can I find the appropriate documentation on what they do and how I should call them?

PS:
I have been able to get something from the tests here: https://github.com/WebAssembly/v8-native-prototype/blob/master/test/mjsunit/wasm/asm-wasm.js

PPS:
Also asked here: http://stackoverflow.com/questions/37837124/understanding-the-wasm-webassembly-prototype

**Comment by jfbastien** [comment]
I saw the stackoverflow question first. Answered there.
