### ISSUE TITLE
v8-native-prototype crashes if you try to export a function with return type i64

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#12]
A simple test example:
```
(module (func (result i64) (i64.const 0)) (export "f" 0))
```
Here's the output (in JS, can't attach binary files)
```
var m = createModule([
    0,   1,   0,   0,   1,   0,   0,   0,   0,   2,  43,   0,   0,   0,  32,   0,
    0,   0,  43,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
    3,   1,  18,   0,   0,   0,   0,   0,   0,   0,   0, 102,   0,   0,   0,   0,
]);
```

This generates the error:
```
#
# Fatal error in , line 0
# unimplemented code
#
...
```

**Comment by titzer** [comment]
This is a known issue; we just need to decide how to module int64's going into and out of JavaScript. We could round them, but that seems...surprising.

**Comment by binji** [comment]
This is particularly annoying because a number of the spec tests rely on i64 values. I wonder if this needs to be written into the wasm design (or is it already?)

**Comment by titzer** [comment]
This issue is because Nick and I basically didn't yet map i64 values to JS
values. We could do something dumb like allocate an object with an upper
and lower half for them, I suppose.

**Comment by titzer** [comment]
Since these should (for now) only show up in assertions, would it be
possible to "desugar" assertions by wrapping them in another wasm function
that checks the values (thus keeping the int64 contained within wasm)?

Alternatively, we could add some v8-native-prototype support for assertions
and then implement C++ code that can run them--or even add bytecodes.

**Comment by binji** [comment]
That's how I do it now, where all assert_* statements get rewritten as a function in the module. The trouble is that one spec test (so far) imports print as print_i64. There's no way to make this work currently.

**Comment by titzer** [comment]
This should be fixed. It no longer crashes, but it silently wraps i64 to i32 and then does conversions. Not ideal and should be fixed, but enough to make progress.
