### ISSUE TITLE
switch statement?

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#17]
The WebAssembly spec repo has an expression-based switch statement; this is tedious to emulate with the current primitives (i.e. if-else cascade), as it requires caching the switch input as well as the switch output, not to mention that handling fallthrough requires duplicating case value checks or bodies. For example, the spec repo switch example:
```
    (return
      (label $l
        (i64.switch (get_local $i)
          (case 0 (return (get_local $i)))
          (case 1 (nop) fallthrough)
          (case 2)  ;; implicit fallthrough
          (case 3 (break $l (i64.sub (i64.const 0) (get_local $i))))
          (case 6 (set_local $j (i64.const 101)) fallthrough)
          (;default;) (get_local $j)
        )
      )
    )

```
reduces to this (I think):
```
(local $input i64)
(local $output i64)
(return
  (label $l
    (set_local $input (get_local $i))
    (block
      (if (i32.eq (get_local $input) (i32.const 0))
        (return (get_local $i))
        (block
          (if (i32.eq (get_local $input) (i32.const 1))
            (nop))
          ;; fallthrough for 1 and 2
          (if (i32.or
                (i32.or
                  (i32.eq (get_local $input) (i32.const 1))
                  (i32.eq (get_local $input) (i32.const 2)))
                (i32.eq (get_local $input) (i32.const 3)))
            (break $l (i64.sub (i64.const 0) (get_local $i)))
            (block
              (if (i32.eq (get_local $input) (i32.const 6))
                (set_local $j (i64.const 101)))
              ;; fallthrough for 6
              (set_local $output (get_local $j))))))))))
```

**Comment by titzer** [comment]
Switch statements in v8-native are a bit underpowered. There are only
basically table switches with and without fallthrough, and they're
statements. At least they need to be made into expressions, or an
expression variant added.

Personally I think that spec'ing switch statements other than simple table
switches was a mistake. But I'll probably take a stab at a general switch
statement anyway.

**Comment by lukewagner** [comment]
> Personally I think that spec'ing switch statements other than simple table switches was a mistake.

Do you mean that, instead of specifying a list of cases, each with a value, you'd specify a `[low, high]` pair and then an array of cases for each element in that range?  Because I'd be down with that: it encourages the codegenerator to think of this as a table switch which is all I think engines should implement; if the consumer wants an if-tree, they should just generate that.  I think this will lead to more predictable performance.

**Comment by titzer** [comment]
On Thu, Oct 1, 2015 at 11:13 PM, Luke Wagner <notifications@github.com>
wrote:

> Personally I think that spec'ing switch statements other than simple table
> switches was a mistake.
>
> Do you mean that, instead of specifying a list of cases, each with a
> value, you'd specify a [low, high] pair and then an array of cases for
> each element in that range? Because I'd be down with that: it encourages
> the codegenerator to think of this as a table switch which is all I think
> engines should implement; if the consumer wants an if-tree, they should
> just generate that. I think this will lead to more predictable performance.
>
Yes; tableswitches only, maybe even starting from zero (user can do their
own subtract).

**Comment by lukewagner** [comment]
Hah, of course.  +1 from me.

**Comment by titzer** [comment]
With a default case and no-fallthrough, then it becomes straightforward to
make it an expression, too.

**Comment by rossberg-chromium** [comment]
SGTM, but wasn't encoding certain forms of goto a use case for fallthrough?

**Comment by lukewagner** [comment]
With `br_switch` in [spec/#98](https://github.com/WebAssembly/spec/pull/98) (`if` is to `br_if` as `switch` is to `br_switch`), fallthrough just works w/o any extra spec support, so I expect it isn't necessary in the higher-level switch.  That being said, I don't think it'd be that complicated to add to the high-level switch, so I'd be in favor of that too.

**Comment by binji** [comment]
switch has been removed in favor of tableswitch, closing.
