### ISSUE TITLE
Check failed: effect_count == control->op()->ControlInputCount() (1 vs. 2)

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#18]
minimized test case that produces the given error:
```
(module
  (func
    (loop (i32.load (i32.const 0)))))
```
Error given:
```
#
# Fatal error in ../../src/compiler/verifier.cc, line 406
# Check failed: effect_count == control->op()->ControlInputCount() (1 vs. 2).
#
```
Byte sequence:
```
var m = createModule([
    0,   1,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,  32,   0,
    0,   0,  38,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    6,   1,  32,   6,  16,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
]);
```

**Comment by titzer** [comment]
Fixed by https://github.com/WebAssembly/v8-native-prototype/commit/9cd7bde9ecba32ac52e849936073e7a2f4d26e68

**Comment by binji** [comment]
I'll confirm when I have access to that test. Can't ssh into my desktop for some reason. :-|

**Comment by binji** [comment]
Tested this with my hand-translated fannkuch. I had a few translation bugs, but after I fixed them everything worked. Ran in about 2x time the equivalent in gcc -O3, probably in no small part due to my naive translation. Cool to see it working though!

**Comment by titzer** [comment]
Awesome! There are also some TurboFan optimizations to turn on yet, so it
could run a bit faster too.
