### ISSUE TITLE
opcode for memory_size

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#20]
The spec repo has an opcode for memory_size, which returns the current size of the linear memory. We should add one to v8-native-prototype too.

**Comment by titzer** [comment]
I was considering the possibility that memory_size might be expressed as
resize_memory(0), but now I realize that it's not good to overload a
changing operation to be a changing/querying operation.

**Comment by titzer** [comment]
Fixed in https://github.com/WebAssembly/v8-native-prototype/commit/a7448c0887b979c1a0be5aa1faa4ea712abbcc7f
