### ISSUE TITLE
unsupported opcodes

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#25]
#88:ExprI32Ctz
#89:ExprI32PopCnt
#114:ExprI64Clz
#115:ExprI64Ctz
#116:ExprI64PopCnt
#121:ExprF32Min
#122:ExprF32Max
#125:ExprF32CopySign
#126:ExprF32Ceil
#127:ExprF32Floor
#128:ExprF32Trunc
#129:ExprF32NearestInt
#141:ExprF64Min
#142:ExprF64Max
#145:ExprF64CopySign
#146:ExprF64Ceil
#147:ExprF64Floor
#148:ExprF64Trunc
#149:ExprF64NearestInt
#162:ExprI64SConvertF32
#163:ExprI64SConvertF64
#164:ExprI64UConvertF32
#165:ExprI64UConvertF64
#170:ExprF32SConvertI64
#171:ExprF32UConvertI64
#176:ExprF64SConvertI64
#177:ExprF64UConvertI64

**Comment by titzer** [comment]
This list should be down to (on x64):

ExprI64SConvertF32:
ExprI64SConvertF64:
ExprI64UConvertF32:
ExprI64UConvertF64:

**Comment by gahaas** [comment]
All opcodes are supported now on x64.
