### ISSUE TITLE
module won't run with unreachable code

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#33]
There is a test from the spec repo:
```
  (func $block (result i32)
    (block $exit
      (break $exit (i32.const 1))
      (i32.const 0)
    )
  )
```

This fails with:
```
 +.../sexpr-wasm/test/spec.js:28: WasmModule::Instantiate(): Compiling WASM function #0:block failed:Result = unreachable code @+6
  +
  +  var module = WASM.instantiateModule(u8a.buffer, ffi);
  +                    ^
  +
```

It is unreachable code, but it should probably compile and run anyway.

**Comment by weilianglin** [comment]
Same issue for below case:
function call(x) {
  x = x | 0;
  if (x) {
    return 1;
  } else {
    return 0;
  }
  return -1;
}

test-wasm.js:1: WasmModule::Instantiate(): Compiling WASM function #0:call failed:Result = unreachable code @+19

**Comment by titzer** [comment]
If the is valid asm.js code (it certainly is valid JS), then we'll have to
lift the unreachable code restriction on wasm.

**Comment by weilianglin** [comment]
I found the similar code when using emscripten to generate asm.js code for fasta.cpp
emcc -O2 -profiling -g2 fasta.cpp -o fasta.js

The code at the end of "function ___dynamic_cast(i1, i2, i3, i4) " like below
function ___dynamic_cast(i1, i2, i3, i4) {
...
 FUNCTION_TABLE_viiiii[HEAP32[(HEAP32[i9 >> 2] | 0) + 24 >> 2] & 3](i9, i6, i8, 1, 0);
 i8 = HEAP32[i6 + 36 >> 2] | 0;
 if (!i8) {
  i14 = (HEAP32[i11 >> 2] | 0) == 1 & (HEAP32[i7 >> 2] | 0) == 1 & (HEAP32[i10 >> 2] | 0) == 1 ? HEAP32[i2 >> 2] | 0 : 0;
  STACKTOP = i5;
  return i14 | 0;
 } else if ((i8 | 0) == 1) {
  if ((HEAP32[i1 >> 2] | 0) != 1 ? !((HEAP32[i11 >> 2] | 0) == 0 & (HEAP32[i7 >> 2] | 0) == 1 & (HEAP32[i10 >> 2] | 0) == 1) : 0) {
   i14 = 0;
   STACKTOP = i5;
   return i14 | 0;
  }
  i14 = HEAP32[i4 >> 2] | 0;
  STACKTOP = i5;
  return i14 | 0;
 } else {
  i14 = 0;
  STACKTOP = i5;
  return i14 | 0;
 }
 return 0;
}

The last return 0 is unreachable. V8-native fails on it.

**Comment by titzer** [comment]
The unreachable code restriction has been lifted.
