### ISSUE TITLE
Exporting i64 to JS wraps to i32

### ISSUE THREAD

**Issue by titzer** [WebAssembly/v8-native-prototype#41]
We took a shortcut to allow i64 to flow into and out of JavaScript by wrapping to i32.

Other solutions: 

1. break down i64 outgoing params to a pair of ints, but what about return values.
2. round i64 to doubles, losing precision, but getting an answer that is "more correct".
3. bitcast i64 to double, but might lose NaN bits.
4. Box i64 as objects that have high and low properties.
5. Wait on JavaScript acquiring a bonafide i64 for itself.

**Comment by wanderer** [comment]
> Wait on JavaScript acquiring a bonafide i64 for itself.

I feel like that is going to take a while. 

4 seems like the best options so far, imo

**Comment by wanderer** [comment]
also how about using an ArrayBuffer?

**Comment by pizlonator** [comment]
How important is it to have i64 flow into and out of JS right now?

-Filip

**Comment by wanderer** [comment]
well the [prototype](https://github.com/ethereum/evm2.0-design/blob/master/eth_interface.md) i'm working on that uses v8, depends on it. So its pretty important to me at least :)
