### ISSUE TITLE
select operator is type-generic

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#51]
In the stmt_expr branch, select has just one opcode (0x5), but in the spec repo it is specified as taking a type: e.g. `i32.select`. Who's right?

**Comment by titzer** [comment]
The design repo lists it as type-parameterized.

**Comment by titzer** [comment]
Select was implemented in https://github.com/WebAssembly/v8-native-prototype/commit/34c49116156df8835f9803361450fbc380a79a1c
