### ISSUE TITLE
Unreachable as implicit return type

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/v8-native-prototype#61]
I think there's a problem with having unreachable in functions which have a return type: e.g. with this module:
```
(module
  (export "foobar" $foobar)
  (func $foobar
    (result i32)
    (unreachable)
))
```
You get:
`test/wasm.js:21: WasmModule::Instantiate(): Compiling WASM function #0:foobar failed:Result = ImplicitReturn expects 1 arguments, only 0 remain @+0`

And with:
```
(module
  (import $abort "" "abort")
  (import $exit "" "exit" (param i32))
  (export "foobar" $foobar)
  (func $foobar
    (param i32)
    (param i32)
    (param i32)
    (result i32)
    (local i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
    (block $BB0_3
    (block $BB0_2
    (set_local 7 (get_local 0))
    (set_local 8 (i32.const 1))
    (set_local 3 (i32.and (get_local 7) (get_local 8)))
    (set_local 10 (i32.const 0))
    (set_local 11 (i32.eq (get_local 3) (get_local 10)))
    (br_if $BB0_3 (get_local 11))
    (set_local 5 (get_local 2))
    (set_local 6 (get_local 1))
    (set_local 9 (i32.const 3))
    (set_local 4 (i32.and (get_local 6) (get_local 9)))
    (set_local 12 (i32.sub (get_local 4) (get_local 3)))
    (set_local 13 (i32.mul (get_local 12) (get_local 4)))
    (set_local 14 (i32.add (get_local 13) (get_local 5)))
    (set_local 15 (i32.const 7))
    (set_local 16 (i32.and (get_local 14) (get_local 15)))
    (set_local 17 (i32.const 5))
    (set_local 18 (i32.eq (get_local 16) (get_local 17)))
    (br_if $BB0_2 (get_local 18))
    (br $BB0_3)
    )
    (call_import $exit (get_local 10))
    (unreachable)
    )
    (call_import $abort)
    (unreachable)
  )
  (export "main" $main)
  (func $main
    (result i32)
    (local i32 i32 i32 i32)
    (set_local 0 (i32.const 3))
    (set_local 1 (i32.const 2))
    (set_local 2 (i32.const 1))
    (set_local 3 (call $foobar (get_local 2) (get_local 1) (get_local 0)))
    (unreachable)
  )
  (memory 0 0
    (segment 0
      ""
    )
  )
)
```
You get:
`test/wasm.js:21: WasmModule::Instantiate(): Compiling WASM function #2:foobar failed:Result = ImplicitReturn[0] expected type int32, found ExprBlock of type <stmt> @+111`

**Comment by binji** [comment]
I haven't pushed a version of sexpr-wasm that generates unreachable yet. Did you implement it yourself?

**Comment by titzer** [comment]
So if your function ends in an unreachable() or otherwise has no successful
path to return a value, that should not be an error, correct?

**Comment by dschuff** [comment]
@binji Oh, I saw https://github.com/WebAssembly/sexpr-wasm-prototype/commit/53a431e87288e334de7ede83c5a0a73f0566f823 and thought it should work but I didn't actually look at the code so I didn't realize that it just skipped it. So yeah, v8 never actually saw the unreachable in this case. But @titzer yes, I think that's correct. The use case is exactly what's here, i.e. a function is supposed to return a value, but the optimizer reduces it to a call to exit or abort.

**Comment by titzer** [comment]
Ok, I plan to remove all unreachable code errors and make v8-native robust
to those corner cases.

**Comment by dschuff** [comment]
Come to think of it I'm not actually sure about the "otherwise has no successful path to return a value" part. I think explicit and implicit returns would still need to pass the type check (e.g. you couldn't just have a nop at the end of a function body that returns a value). Unreachable is sort of the safety net for that (you could have unreachable at the end instead, and then the typecheck would pass and the behavior would be well-defined). That's sort of a separate issue from a function that e.g. had an unconditional return expression followed by some more code (which I think is probably valid but v8 currently doesn't like).

**Comment by sunfishcode** [comment]
I haven't followed the sexpr-wasm-prototype changes here closely, but my ears perked up at the mention of "corner cases". If there are interesting corner cases, let's add tests for them to the spec testsuite! :-)

**Comment by titzer** [comment]
Unreachable code is no longer an error in v8-native-prototype.
