### ISSUE TITLE
Can't break to the tableswitch label from the table

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#88]
This code fails in v8-native:
```
(module
  (func
    (tableswitch $a (i32.const 0)
      (table (br $a)) (case $b)
        (case $b (i32.const 1)))))
```
This gives the error: `WasmModule::Instantiate(): Compiling WASM function #0:<?> failed:Result = improper branch in tableswitch @+5`

The tableswitch block scope isn't pushed until the tableswitch opcode is reduced, so the label is not yet valid.

**Comment by titzer** [comment]
Fixed by https://github.com/WebAssembly/v8-native-prototype/commit/436dd8620179d304c6f64dde47d0b10b1a27fd81.
