### ISSUE TITLE
return type mismatch caused by Trap Code

### ISSUE THREAD

**Issue by weilianglin** [WebAssembly/v8-native-prototype#97]
Hi 

In the trap code, after throw, it always return the 0xdeadbeef, the type of which is int32 like below, 

      // End the control flow with returning 0xdeadbeef
      TFNode* ret_dead =
          g->NewNode(graph->common()->Return(),
                     graph->Int32Constant(0xdeadbeef), *effect, *control);
      end = ret_dead;
    }

It seems to lead to return type mismatch if the return type of the function is rather than int32 type, like float32 or float64.  Any thoughts?

Thanks
-Weiliang

**Comment by titzer** [comment]
Yeah, that's a bug, but that should only show up in tests. WASM code generated from WASM.instantiateModule() will call the runtime and throw a JS-level exception.

**Comment by weilianglin** [comment]
well, now I met an issue during the register allocation of TurboFan. At the fixed register allocation stage, the return double value has a fixed double register (xmm1) and the RA will check whether the type of return value is a float type (f32 or f64), otherwise, it will crash. 

Only DEBUG version d8 has this issue.

**Comment by titzer** [comment]
I've fixed the type check failing in https://github.com/WebAssembly/v8-native-prototype/commit/61eb965441fd963c7092c455b7f7b2b75c2c1245, but the register allocator issue is due to the trap code, which apparently does appear in production.

**Comment by weilianglin** [comment]
Actually, I don't quite understand why this bug only shows up in test. The code like below will always lead to type check failure in RA. 
function getF64(index){
  index=index|0;
  return +h[index>>3]; // h is a float64 typed array
}

Maybe we could make RA more clever to ignore the dead code.

**Comment by gahaas** [comment]
I changed the code now, so that the return type caused by trap code is the same as the return type of the function. (https://codereview.chromium.org/1519013003)

**Comment by weilianglin** [comment]
Hi @gahass, 

It works! Thanks a lot for this fixing.

Thanks
-Weiliang
